Revert "bootlinux: fix os detection for 9p build dependency installation"
I've observed that the "build kernel on a separate node" tasks are
now failing when my controller is Fedora 42 and the selected target
nodes are running Debian 11. Daniel has confirmed this:

TASK: Install packages we care about [kci-19183690762-181-nvme]
FAILED - RETRYING: [kci-19183690762-181-nvme -> localhost]: Install packages we care about (3 retries left).
FAILED - RETRYING: [kci-19183690762-181-nvme -> localhost]: Install packages we care about (2 retries left).
FAILED - RETRYING: [kci-19183690762-181-nvme -> localhost]: Install packages we care about (1 retries left).
⠀⠀FAILED: [kci-19183690762-181-nvme] => ['Could not detect which major revision of dnf is in use, which is required to determine module backend.', 'You should manually specify use_backend to tell the module whether to use the dnf4 or dnf5 backend})']
Error: : Task failed: Action failed: ('Could not detect which major revision of dnf is in use, which is required to determine module backend.', 'You should manually specify use_backend to tell the module whether to use the dnf4 or dnf5 backend})')
Origin: /data4-xfs/gh/actions-runner/kdevops-ci-0019/_work/kdevops/kdevops/playbooks/roles/bootlinux/tasks/install-deps/redhat/main.yml:8:3

We believe that commit 75f870367e16 ("bootlinux: Update grub on
Debian after installing debs") is the culprit. Revert that commit
so we can find a fix that doesn't break the bootlinux_builder
tasks.

Acked-by: Daniel Gomez <da.gomez@samsung.com>
Signed-off-by: Chuck Lever <chuck.lever@oracle.com>