github: configure: fix parallel git-config
Fix parallel git-config commands by making them local to the cloned repo
in the workflow run.

Fixes error:
+ git config --global --add safe.directory '*'
+ git config --global user.name kdevops
error: could not lock config file /home/gh/.gitconfig: File exists

Fixes: 4dd76849 ("github: refactor into reusable actions and workflows")
Signed-off-by: Daniel Gomez <da.gomez@samsung.com>