Revert "github: drop redundant kdevops checkout"
Revert checkout and use custom unique workdir path.

GitHub needs to checkout first to use project workflow files. Restore it
but use the custom path ("Relative path under $GITHUB_WORKSPACE to place
the repository") for concurrent jobs in the same runner. And cleanup
before fetching (clean: true -> Whether to execute `git clean -ffdx &&
git reset --hard HEAD` before fetching; default true).

https://github.com/actions/checkout

  # Whether to execute `git clean -ffdx && git reset --hard HEAD` before fetching
    # Default: true
    clean: ''

Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under
'/data4-xfs/gh/actions-runner/kdevops-ci-0004/_work/kdevops/kdevops/.git
hub/actions/setup'. Did you forget to run actions/checkout before
running your local action?

This reverts commit 9f04539154d10144c085a3bb72b30bd345d1bc57.

Signed-off-by: Daniel Gomez <da.gomez@samsung.com>